### ISSUE TITLE
Recurrent NNs

### ISSUE THREAD

**Issue by andres-ulloa** [Fraunhofer-IMS/AIfES_for_Arduino#1]
Really appreciate the work you guys are doing here. Library is great and a strong alternative to Tensorflow Lite Micro - arguably even better given how easy it is to load and update new weights. Since a lot of sensor data makes sense with time as a dimension, it begs the question though; is there any chance we are getting support for recurrent neural networks?  More specifically GRUs and LSTMs.  

Regards.

**Comment by AIfES-Pierre** [comment]
Hi Andrés,

thank you for your positive feedback. :)

Recurrent neural networks will come in the future. But before that, there are other features that are already in the pipeline.

Here is an overview of the planned roadmap:
- Fixpoint  Q31 (32 Bit integer) and Q7 (8 Bit integer) support including training
- Full CNN support with training
- Reinforcement learning (Is worked on in parallel and can also come earlier)
- Recurrent neural networks (with different NN structures)

Besides the features in AIfES, we are also working on useful tools to create models more easily or to import networks automatically. For example, the paid version already includes an automated Python wrapper for Keras and TF models.

By the way, we have an account with the Arduino project hub. Here we will present new projects:
[https://create.arduino.cc/projecthub/aifes_team/aifes-color-detection-demo-772811](url)

Regards,
Pierre
