### ISSUE TITLE
Support for Sequential Models

### ISSUE THREAD

**Issue by expeon07** [Fraunhofer-IMS/AIfES_for_Arduino#16]
Hi! Are sequential models supported in this library?

**Comment by AIfES-Pierre** [comment]
Hi @expeon07 

do you mean a Sequential Keras model? Sure, a feedforward neural network works fine. CNNs coming soon 😉

Best,
Pierre

**Comment by expeon07** [comment]
Yes, a sequential model. I just wanted to confirm but I think the examples you had have sequential Keras models as well.
Thank you!
