### ISSUE TITLE
Feature Request: Support for Arduino PortentaH7 Vision and Sound

### ISSUE THREAD

**Issue by hpssjellis** [Fraunhofer-IMS/AIfES_for_Arduino#3]
Really impressed with this Arduino Library so far.

Any plans for future support for the Portenta Vision Shields?

I hve some draft examples using Edge Impulse or my own generic ML @rocksetta methods converting from TensorflowJS to TensorflowMicro c header files.

**Comment by hpssjellis** [comment]
Answered my own question. This library runs really great and super fast on the Arduino Portenta. I am really impressed. If you need an Ambassador, please reach out.

Jeremy Ellis twitter @rocksetta

**Comment by hpssjellis** [comment]
Oops, closed that before giving you a chance to reply. The present library works great, yes it has no vision yet. Is that in the works?

**Comment by AIfES-Pierre** [comment]
Hi Jeremy,

I have seen the video. Thanks for that. Cool that you started without any preparation and it worked right away. AIfES should run on almost any Arduion or Arduino compatible board. 

AIfES can also be used together with the Vision Shield but we don't have any examples for that at the moment. This will probably only become really interesting when we have integrated the ConvNets. Here is a little roadmap of what is planned:

- AIfES Fixpoint: Besides float 32, Q31 (32 bit integer) and Q7 (8 bit integer) will be supported. The quantization of the weights can then be done directly in AIfES.
- AIfES Express: Strongly simplified functions for feed forward nets. Then, inference and training can be performed with one function call each. A bit like Keras for TensorFlow but directly integrated into AIfES.
- ConvNets: Inference and training for ConvNets. This will be cool.

For everything else, it's best to contact us via our contact form:
https://www.ims.fraunhofer.de/en/Business-Unit/Industry/Industrial-AI/Artificial-Intelligence-for-Embedded-Systems-AIfES/AIFES_Cooperation.html


Best regards
Pierre
